name: Upload Transcripts

on:
  push:
    branches:
      - main
    paths:
      - transcripts/**

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Transcripts
      run: |
        ls transcripts/  # Elenca i file nella cartella transcripts per il debug

    - name: Copy Transcripts
      run: |
        cp -r transcripts/* ./  # Copia i transcript nella root del progetto

    - name: Configure Git
      run: |
        git config --local user.name "SouL321321"
        git config --local user.email "battleofcod@gmail.com"

    - name: Commit and Push
      run: |
        git add .  # Aggiungi tutti i file
        git commit -m "Aggiornamento dei transcript" || echo "Nessun cambiamento da caricare"
        git push
